OpenChain Telco SBOM Specification.md

Probably pointless given that we need to fill out the content more before getting down to this level, but I was reading through the doc again, so I thought I'd take a sweep while I was at it.

Minor tweaks to spelling, punctuation, etc.

---

OpenChain Telco SBOM Specification.md

Fix definition of Entity

---

OpenChain Telco SBOM Specification.md

Fix Data Format

---

OpenChain Telco SBOM Specification.md

Fix SPDX definition

---

OpenChain Telco SBOM Specification.md

Add SPDX version to data format requirements

---

OpenChain Telco SBOM Specification.md

Update Data Format Verification material/reference material

Data Format Verification material/reference material

---

OpenChain Telco SBOM Specification.md

NTIA Minimum elements

---

OpenChain Telco SBOM Specification.md

Prposal for 3.11	SBOM in a SaaS deployment

---

OpenChain Telco SBOM Specification.md

Proposal for 3.12	SBOMs for containers

---

OpenChain Telco SBOM Specification.md

Proposal for 3.12.2	Rationale

---

OpenChain Telco SBOM Specification.md

Proposal for 3.14	SBOM Merger

---

OpenChain Telco SBOM Specification.md

Proposal for 3.15	SBOM Confidentiality

---

OpenChain Telco SBOM Specification.md

Proposal for 3.15.2	Rationale

---

OpenChain Telco SBOM Specification.md

Fix SBOM definition

---

OpenChain Telco SBOM Specification.md

Add definition of Transitive dependencies

---

OpenChain Telco SBOM Specification.md

Added some proposed language for us to discuss.

Usage statement and "header"

---

OpenChain Telco SBOM Specification.md

Fixing the naming of Tag:Value and inserting a reference to the SPDX specification.

Tag:Value reference fix. 

---

OpenChain Telco SBOM Specification.md

I propose we either examine if we can align with OpenSFF on if Sigstore would work, or delete this item and reintroduce it in a possible v.1.1 update to the specification.

SBOM Security and Verification

---

OpenChain Telco SBOM Specification.md

Proposal for 3.10	SBOM Scope

---

OpenChain Telco SBOM Specification.md

Update Method of SBOM delivery

---

OpenChain Telco SBOM Specification.md

Changed Data Format to format where it applies to the format of the SPDX (Tag:Value).

Update OpenChain Telco SBOM Specification.md

---

OpenChain Telco SBOM Specification.md

CISA has now officially published the definition of the SBOM types.

Update CISA link

---

OpenChain Telco SBOM Specification.md

"Entity" in Chapter 2, the "the" is doubled.

Editorial corrections

---

OpenChain Telco SBOM Specification.md

Add text to Chapter 4 that SBOM requesters can refer to.

Notice of Compliance for SBOM requester #58

---

OpenChain-Telco-SBOM-Guide_EN.md
OpenChain-Telco-SBOM-Guide_JP.md

Update JP.md to adapt to #81
Corrected the web link address in Section 4 in EN.md

Update JP.md and Correction of web link in EN.md

---

OpenChain-Telco-SBOM-Guide_ZH_HANS.md

Very happy to see the emergence of OpenChain Telco SBOM Guide. I am an infra engineer in Bytedance and now do software supply chain license compliance governance work. Here I have translated it into a Simplified Chinese version. Thanks for your PR review.

add OpenChain-Telco-SBOM-Guide_ZH_HANS.md

---

README.md
tools/README.md
tools/openchain-telco-sbom-validator.py
tools/requirements.txt

It's a tool to validate SBOMs against the OpenChain Telco SBOM Guide
Update README (remove wiki that is not used)

Add openchain-telco-sbom-validator.py

---

tools/openchain_telco_sbom_validator/setup.cfg
tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/__init__.py
tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/cli.py
tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/reporter.py
tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/validator.py
tools/openchain_telco_sbom_validator/testing/test-test.sh

* The package level extensions were called with the whole SPDX Document in stead of the Package this is fixed in this pr
* Couple of fixes to how the module is organized after implementing the usage of it
* CLI command name harmonized to the package name

Fixes to packaging, package functions and the CLI

---

.github/workflows/test-validator.yml

This pr adds automatic tests to the validator. The output is a bit messy at the moment due to an issue with how GitHub is using the [testing tool](https://github.com/thorsteinssonh/bash_test_tools/issues/8).

Automatic test

---

tools/openchain_telco_sbom_validator/setup.cfg
tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/cli.py
tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/reporter.py
tools/openchain_telco_sbom_validator/testing/test-test.sh

Using the --version parameter
$ openchain-telco-sbom-validator --version
OpenChain Telco SBOM Validator version 0.1.8

Adding capability to report own version

---

OpenChain-Telco-SBOM-Guide_1.1_draft_EN.md

Fixes https://github.com/OpenChain-Project/Telco-WG/issues/122

sbomasm is a better SBOM merge tool

---

OpenChain-Telco-SBOM-Guide_1.1_draft_EN.md

Fixes https://github.com/OpenChain-Project/Telco-WG/issues/128

Do not make FilesAnalyzed mandatory

---

OpenChain-Telco-SBOM-Guide_1.1_draft_EN.md

Fixes https://github.com/OpenChain-Project/Telco-WG/issues/138

Remove PackageChecksum from list of MANDATORY Package information

---

tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/validator.py
tools/openchain_telco_sbom_validator/unittests/test_validator_package.py

Remove "package originator" from the error message.

We require PackageSupplier

---

OpenChain-Telco-SBOM-Guide_ZH_HANT.md

This PR introduces a Traditional Chinese (zh-TW) translation of the OpenChain Telco SBOM Guide, providing accessibility for Chinese-speaking professionals in the telecommunications and cybersecurity industries.
Signed-off-by: SZ Lin (林上智) <szlin@szlin.tw>

Add Traditional Translation for OpenChain Telco SBOM Guide

---

OpenChain-Telco-SBOM-Guide_ZH_HANT.md

Refine Traditional Chinese translations

Fix: update Traditional Chinese translation

---

OpenChain-Telco-SBOM-Guide_1.1_draft_EN.md

A RECOMMENDED syntax is given for CISA SBOM Types.

Update History section

---

tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/cli.py
tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/reporter.py
tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/validator.py

Validate recursively. Same as “--reference-logic checksum-all”.
Add "-v" as synonym of "--version"
Update Copyright to 2024-2025
Add header in reporter.py

Add --recursive option

---

OpenChain-Telco-SBOM-Guide_1.0_ZH_HANT.md

1. Add OpenChain-Telco-SBOM-Guide_1.1_ZH_HANT.md
2. Rename existing translation file to OpenChain-Telco-SBOM-Guide_1.0_ZH_HANT.md

Add Traditional Chinese translation v1.1 and rename v1.0 file

---

tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/validator.py

Test was too strict.
The presence of the hyphen is RECOMMENDED but not MANDATORY.

Fix https://github.com/OpenChain-Project/Telco-WG/issues/136

---

tools/openchain_telco_sbom_validator/setup.cfg
tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/validator.py

Implement strict for tool name and version

Prepare for version 0.3.1

---

tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/cli.py
tools/openchain_telco_sbom_validator/src/openchain_telco_sbom_validator/validator.py

This flag allows to list fields with value NOASSERTION

Implement --noassertion flag

---

tools/openchain_telco_sbom_validator/open-source-compliance-artifacts/openchain-telco-sbom-validator-0.3.1.spdx

Add SBOM for validator version 0.3.1

---

OpenChain-Telco-SBOM-Guide_KR.md
README.md

This is a Korean translation of the guide version 1.1.

add Korean translation
